Datos arquitectonicos

In [1]:
import numpy as np
import pandas as pd
from StructuralDesign import StructuralDesign

# Datos de entrada
materiales = {
    'A_sec': 36,
    'A_trab': 50,
    'E': 2100000,
    'fc': 210
}

datos_arquitectonicos = {
    'L1': 6.5,
    'L2': 6,
    'L3': 6.3,
    'L4': 6.5,
    'Pisos': 2,
    'Cm': 0.5,
    'Cv': 0.2,
    'He': 3,
    'Cu': 1.2 * 0.5 + 1.6 * 0.2
}

propiedades_vigas = {
    'vigas_sec_prop': {
        'iz': {'Acero': 36, 'bf': 12, 'tf': 0.6, 'h': 30, 'tw': 0.3},
        'der': {'Acero': 36, 'bf': 12, 'tf': 0.6, 'h': 31, 'tw': 0.4}
    },
    'vigas_trab_prop': {
        'iz': {'Acero': 50, 'bf': 16, 'tf': 1, 'h': 41, 'tw': 0.6},
        'der': {'Acero': 50, 'bf': 16, 'tf': 1, 'h': 37, 'tw': 0.5}
    },
    'vigas_secundarias': {
        'iz': {'Acero': 36, 'Lv': 6.3, 'Lt': 6.5, 'Vigas': 4},
        'der': {'Acero': 36, 'Lv': 6.3, 'Lt': 6, 'Vigas': 3}
    },
    'vigas_trab': {
        'iz': {'Acero': 50, 'Tipo': 'Central', 'Lv': 6.3, 'Lt': 6.5, 'Num': 4},
        'der': {'Acero': 50, 'Tipo': 'Central', 'Lv': 6.3, 'Lt': 6, 'Num': 3}
    }
}

propiedades_columna = {
    'columna': {'Acero': 50, 'Relleno hormigon': 'SI', 'b': 31, 'h': 31, 'e': 0.4},
    'Atiesadores': {
        'Sentido_b': {'Num': 1, 'I': 4, 'e': 0.3},
        'Sentido_h': {'Num': 1, 'I': 4, 'e': 0.3}
    }
}

propiedades_conexiones = {
    'Prop_RBS': {
        'iz': {'a': 8, 'b': 28, 'c': 3.6, 'E_pat': 80, 'tp': 1, 'hh': 1.2, 'bp': 5, 'E_alma': 60},
        'der': {'a': 8, 'b': 28, 'c': 3.6, 'E_pat': 80, 'tp': 1, 'hh': 1.2, 'bp': 5, 'E_alma': 60}
    },
    'Prop_end_plate_4E': {
        'iz': {'Acero': 50, 'Tipo': 'A490', 'Perno': 1, 'tp': 2.5, 'bp': 20, 'g': 15.2, 'pf': 4, 'E': 80},
        'der': {'Acero': 50, 'Tipo': 'A490', 'Perno': 1, 'tp': 2.5, 'bp': 20, 'g': 15.2, 'pf': 4, 'E': 80}
    },
    'Prop_end_plate_4ES': {
        'iz': {'Acero_ep': 50, 'Tipo': 'A490', 'Perno': 1, 'tp': 2.5, 'bp': 20, 'g': 15.2, 'pf': 4.4, 'de': 4.4, 'E': 80}, 
        'der': {'Acero_ep': 50, 'Tipo': 'A490', 'Perno': 1, 'tp': 2.5, 'bp': 20, 'g': 15.2, 'pf': 4, 'de': 4.4, 'E': 80}
    },
    'Diafragma_externo': {
        'iz': {'Ln': 30, 'td': 1.2, 'Acero_de': 50, 'E_patin_diaf': 60},
        'der': {'Ln': 32, 'td': 1.2, 'Acero_de': 50, 'E_patin_diaf': 60}
    },
    'Prop_WUF_W': {
        'iz': {'E': 100, 'tp': 0.6, 'a': 0.6, 'Acero': 36},
        'der': {'E': 100, 'tp': 0.6, 'a': 0.6, 'Acero': 36}
    }
}


parametros_conexiones = {
    'iz': {
        'angulo_apernado': {'Perno': 3/8, 'hp': 15, 'Lbord': 3, 'bp': 6},
        'angulo_soldado': {'E': 60, 'g': 0.3, 'hp': 15, 'tp': 0.3, 'bp': 6},
        'asiento_apernado': {'Perno': 3/8, 'bp': 6},
        'asiento_soldado': {'E': 60, 'bp': 5, 'tp': 0.3},
        'alma_alma': {'E': 60, 'hs': 15, 'g': 0.3}
    },
    'der': {
        'angulo_apernado': {'Perno': 3/8, 'hp': 15, 'Lbord': 3, 'bp': 6},
        'angulo_soldado': {'E': 60, 'g': 0.3, 'hp': 15, 'tp': 0.3, 'bp': 6},
        'asiento_apernado': {'Perno': 1/2, 'bp': 6},
        'asiento_soldado': {'E': 60, 'bp': 5, 'tp': 0.4},
        'alma_alma': {'E': 60, 'hs': 16, 'g': 0.3}
    }
}

# 1. Initialize the StructuralDesign object
structural_design = StructuralDesign(
    materiales,
    datos_arquitectonicos,
    propiedades_vigas,
    propiedades_columna,
    propiedades_conexiones,
    parametros_conexiones
)

structural_design._calcular_propiedades_iniciales()

# To calculate RBS connection for the 'iz' (left) side:
structural_design.calculate_rbs_connection('iz')

# # To calculate End Plate 4E connection for the 'der' (right) side:
# structural_design.calculate_end_plate_4e_connection('der')

# To calculate all advanced connections for both sides:
for lado in ['iz', 'der']:
    structural_design.calculate_rbs_connection(lado)
    # structural_design.calculate_end_plate_4e_connection(lado)
    # structural_design.calculate_end_plate_4es_connection(lado)
    # structural_design.calculate_Diafragma_externo_connection(lado)
    # structural_design.calculate_wuf_w_connection(lado)

# 3. After calculating, you can display or export the results:
structural_design.mostrar_resultados()
# structural_design.exportar_a_excel()

--- Propiedades de las Vigas Secundarias ---

    Sección     Parámetro Izquierda (Valor) Derecha (Valor) Unidad
0   General           cte            28.811          28.811    cte
1   General           cf1             8.643           8.643    cf1
2   General           cf2            10.948          10.948    cf2
3   General           cw1            70.587          70.587    cw1
4   General           cw2            108.33          108.33    cw2
5   General             A             23.04           26.32    cm²
6   General          Peso            18.086          20.661   kg/m
7   General            Ix          3709.325        4209.528    cm⁴
8   General            Zx           273.888         307.684    cm³
9   General             h                30              31     cm
10  General   Condición h              COMP            COMP      -
11  General            bf                12              12     cm
12  General  Condición bf              COMP            COMP      -
13  General            Ry               1.3             1.3      -
14  General            tf               0.6             0.6     cm
15  General            tw               0.3             0.4     cm

--- Propiedades de las Vigas Trabe ---

    Sección     Parámetro Izquierda (Valor) Derecha (Valor) Unidad
0   General           cte            24.447          24.447    cte
1   General           cf1             7.334           7.334    cf1
2   General           cf2              9.29            9.29    cf2
3   General           cw1            59.895          59.895    cw1
4   General           cw2            91.921          91.921    cw2
5   General             A              55.4            49.5    cm²
6   General          Peso            43.489          38.858   kg/m
7   General            Ix         15768.617       12157.125    cm⁴
8   General            Zx            868.15         729.125    cm³
9   General             h                41              37     cm
10  General   Condición h              COMP            COMP      -
11  General            bf                16              16     cm
12  General  Condición bf              COMP            COMP      -
13  General            Ry               1.1             1.1      -
14  General            tf                 1               1     cm
15  General            tw               0.6             0.5     cm

--- Resultados de Vigas Secundarias ---

   Sección Parámetro  Izquierda (Valor)  Derecha (Valor)  Unidad
0  General        fy           2529.866         2529.866  kg/cm²
1  General  S_tablas          25172.218        28102.949     cm³
2  General         W              7.672            8.850  tonf/m
3  General        Mu              6.041            6.970  tonf·m
4  General        Mr              6.236            7.006  tonf·m
5  General       D_C              0.969            0.995       -

--- Resultados de Vigas Trabe ---

   Sección Parámetro  Izquierda (Valor)  Derecha (Valor)  Unidad
0  General        fy           3513.703         3513.703  kg/cm²
1  General       cv1             60.132           60.132       -
2  General       cv2             74.892           74.892       -
3  General        cv              0.880            0.813       -
4  General        Mu             20.263           16.858  tonf/m
5  General        Mr             27.454           23.057  tonf·m
6  General       D_C              0.738            0.731       -
7  General        Pi              7.793            8.991    tonf

--- Diseño de Columnas ---

Columna

         Valor  Unidad
Prx    308.035    tonf
Pry    327.233    tonf
D_C      0.281       -
Mp      57.388  tonf·m
Imin     0.241     cm⁴
fy    3513.703  kg/cm²

--- Conexiones (Vigas Secundarias) ---

             Sección Parámetro  Izquierda (Valor)  Derecha (Valor)  Unidad
0          Alma Alma        Vu              3.836            4.425    tonf
1          Alma Alma         E             60.000           60.000  kg/cm²
2          Alma Alma        hs             15.000           16.000      cm
3          Alma Alma        Rs              7.286           10.362    tonf
4    Angulo Apernado        Vu              3.836            4.425    tonf
5     Angulo Soldado        Vu              3.836            4.425    tonf
6     Angulo Soldado         E             60.000           60.000  kg/cm²
7     Angulo Soldado        Rs              6.072            6.072    tonf
8   Asiento Apernado        Vu              3.836            4.425    tonf
9    Asiento Soldado        Vu              3.836            4.425    tonf
10   Asiento Soldado         E             60.000           60.000  kg/cm²
11   Asiento Soldado        Rs              4.048            5.397    tonf

--- Resultados de Conexiones Avanzadas RBS ---

            Sección  Parámetro  Izquierda (Valor)  Derecha (Valor)   Unidad
0      Chequeo Alma     Rs_CJP        5401264.933      4810962.755     tonf
1      Chequeo Alma  Rs_filete        1949413.914      1798296.557     tonf
2      Chequeo Alma          g              0.800            0.800       cm
3      Chequeo Alma         hp             36.600           32.600       cm
4     Chequeo Patin         Ft             79.939           72.575     tonf
5     Chequeo Patin         Rs             89.951           89.951     tonf
6   Chequeo A Corte         Vn             43.411           29.980     tonf
7   Chequeo A Corte         Vu             28.155           24.064     tonf
8   Chequeo A Corte       h/tw             68.333           74.000        -
9   Propiedades Rbs      E_pat             80.000           80.000  kgf/cm²
10  Propiedades Rbs          a              8.000            8.000       cm
11  Propiedades Rbs          b             28.000           28.000       cm
12  Propiedades Rbs          c              3.600            3.600       cm
13   Resultados Rbs         Mf             31.976           26.127   tonf·m
14   Resultados Rbs        Mpe             33.555           28.181   tonf·m
15   Resultados Rbs    Mpr_con             26.908           21.796   tonf·m
16   Resultados Rbs   Mpr_viga             39.716           33.427   tonf·m
17   Resultados Rbs         Vn             43.411           29.980     tonf
18   Resultados Rbs         Vu             28.155           24.064     tonf
19   Resultados Rbs       Zrbs            580.150          469.925      cm³
20   Resultados Rbs         sh             18.000           18.000       cm

No hay resultados para conexiones End Plate 4E. Ejecute el cálculo correspondiente primero.
No hay resultados para conexiones End Plate 4ES. Ejecute el cálculo correspondiente primero.
No hay resultados para conexiones Diafragma Externo. Ejecute el cálculo correspondiente primero.
No hay resultados para conexiones WUF-W. Ejecute el cálculo correspondiente primero.